name: CI + Deploy

on:
  push:
    branches: [2prod]

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Cloner le dépôt
        uses: actions/checkout@v3

      - name: Installer Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Installer les dépendance
        run: npm install

      - name: Lancer les tests unitaires (Jest)
        run: npm run test

      - name: Lancer les tests Cypress
        uses: cypress-io/github-action@v6
        with:
          start: npm run dev
          wait-on: http://localhost:5173
          wait-on-timeout: 60

      - name: Build du projet
        run: npm run build

      - name: Déploiement sur GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
